name: "Upload SARIF"
# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every at 00:00 on Sunday UTC time.
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
    # This step checks out a copy of your repository.
    - name: Compile
      run: |
        CLMonitor.exe
        gcc -c -Wall -Wextra -Wpedantic p.c
        CLMonitor.exe analyze -l ris.plog
        PlogConverter.exe ris.plog -t sarif -n results
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif
